<p>Lorem ipsum dolor sit amet, lobortis vestibulum ligula, in et suscipit ante. 
In semper nibh a cras. Magna mattis est integer viverra dolor. Voluptatem risus 
lectus, elit et odio ultrices torquent fermentum, sit et elementum tincidunt 
magna cras, mauris suscipit aliquam consectetuer erat arcu. Eu nascetur dictum,
et nonummy neque sapien condimentum torquent pellentesque, in velit eu diam 
mollis nec interdum, aliquam etiam. At at proin rhoncus porttitor pharetra, 
felis sed libero massa in. Vestibulum at.</p>

<p>We wouldn't want to display half a page come an error!</p>

<?php throw new OutOfRangeException('Too many latin words :(') ?>